# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('countryname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('cityid', models.ForeignKey(db_column='cityid', on_delete=django.db.models.deletion.CASCADE, to='ViaSafe.Cities')),
                ('countryid', models.ForeignKey(db_column='countryid', on_delete=django.db.models.deletion.CASCADE, to='ViaSafe.Countries')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=100)),
                ('countryid', models.ForeignKey(db_column='countryid', on_delete=django.db.models.deletion.CASCADE, to='ViaSafe.Countries')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('passwordhash', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='locations',
            name='stateid',
            field=models.ForeignKey(db_column='stateid', on_delete=django.db.models.deletion.CASCADE, to='ViaSafe.States'),
        ),
        migrations.AddField(
            model_name='locations',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='ViaSafe.Users'),
        ),
        migrations.AddField(
            model_name='cities',
            name='stateid',
            field=models.ForeignKey(db_column='stateid', on_delete=django.db.models.deletion.CASCADE, to='ViaSafe.States'),
        ),
    ]
